"""Representative payloads; AML_ADDRESS is the supplied complete example.

Unspecified string values are illustrative, not invented enum restrictions."""

AML_ADDRESS = {'data': {'schemaVersion': '1.0',
          'overallRiskScore': 100,
          'breakdown': {'exposure': {'score': 82.4,
                                     'activityExposure': [{'category': 'hacking', 'share': 12.3},
                                                          {'category': 'userAccountCompromise',
                                                           'share': 22.5},
                                                          {'category': 'stolenAssets',
                                                           'share': 8.2}],
                                     'complianceExposure': [{'category': 'sanctionsExposure',
                                                             'share': 11.5,
                                                             'authorities': [{'authority': 'UK',
                                                                              'share': 2.5},
                                                                             {'authority': 'EU',
                                                                              'share': 3.5},
                                                                             {'authority': 'UN',
                                                                              'share': 1.5}],
                                                             'authorityNotProvidedShare': 4},
                                                            {'category': 'jurisdictionalRiskContext',
                                                             'share': 8,
                                                             'details': [{'category': 'sanctionsRestrictedJurisdiction',
                                                                          'share': 3},
                                                                         {'category': 'fatfCallForActionJurisdiction',
                                                                          'share': 5}]},
                                                            {'category': 'otherComplianceRisk',
                                                             'share': 1.3}],
                                     'counterpartyExposure': [{'category': 'decentralizedExchange',
                                                               'share': 19.2},
                                                              {'category': 'centralizedExchange',
                                                               'share': 7.2}],
                                     'unclassifiedExposure': {'share': 9.8}},
                        'externalReports': {'score': 75,
                                            'activityExposure': [{'category': 'fraudulentSchemes',
                                                                  'share': 100}]},
                        'fatf': {'score': 100,
                                 'flags': [{'flow': 'in',
                                            'category': 'sanctionsExposure',
                                            'count': 5,
                                            'authorities': ['UN']},
                                           {'flow': 'out', 'category': 'hacking', 'count': 17}]},
                        'tokenFlags': {'score': 100,
                                       'flags': [{'category': 'assetRestriction',
                                                  'count': 1,
                                                  'asset': 'usdt'}]}},
          'attribution': {'owners': ['Known service operator'],
                          'cluster': {'names': ['Exploit-related cluster'],
                                      'score': 100,
                                      'activityExposure': [{'category': 'hacking', 'share': 100}]},
                          'assetRestrictions': [{'asset': 'usdt'}]},
          'reportId': 'fa78dfdc-e69d-4bf6-a092-f824bbb24721'}}

AML_TRANSACTION = {'data': {'schemaVersion': '1.0',
          'riskScore': 25.5,
          'counterparties': {'in': {}, 'out': {}},
          'activityExposure': [{'category': 'hacking', 'share': 12.3}],
          'complianceExposure': [],
          'counterpartyExposure': [],
          'unclassifiedExposure': {'share': 9.8}}}

ORDER = {'data': {'id': '44a33415-21f6-45a9-b529-91e6503f6c1b',
          'resource_type': 'energy',
          'target_address': 'TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
          'status': 'charged',
          'volume': 1,
          'duration': 'test-duration',
          'txid': 'test-tx',
          'price_usd': '0.1',
          'failure_code': '',
          'last_error': '',
          'created_at': '2026-10-01T00:00:00Z',
          'updated_at': '2026-10-01T00:00:01Z',
          'charged_at': '2026-10-01T00:00:01Z'}}

WALLET = {'data': {'message': 'Check complete',
          'walletAddress': 'test-address',
          'status': 'ok',
          'probabilityFraud': '0.0421858616',
          'chain': 'ETH'}}

RUG_PULL = {'data': {'message': 'Check complete',
          'contractAddress': '0xtest-contract',
          'status': 'ok',
          'probabilityFraud': '0.0421858616',
          'risk_score': 0.1,
          'chain': 'ETH'}}

ADDRESS_STATUS = {'data': {'address': 'TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
          'status': 'active',
          'activation_estimate_usd': '0.1',
          'activation_price_trx': '1'}}

ACTIVATION_ESTIMATE = {'data': {'activation_price_trx': '1', 'activation_estimate_usd': '0.1'}}
